// ENTRÉE DIRECTE « X vs Y » — une commande, une vidéo de 40 s. Hors-ligne, gratuite.
//
//   npm run match -- Spain Portugal
//   npm run match -- Mexico Brazil --score 2-1 --competition "Coupe du Monde"
//   npm run match -- France Espagne --voice=elevenlabs      (opt-in payant)
//
// Les effectifs viennent de la bibliothèque semée (`pronoclip-data/squads/`) : l'effectif
// est une ENTRÉE, jamais une invention du modèle. Le score et les buteurs sont produits
// par le moteur LOCAL. Aucun réseau, aucun MCP, aucune clé.
//
// Si une équipe n'est pas semée, on le dit clairement avec la marche à suivre — jamais
// de joueurs fabriqués en douce.

import 'dotenv/config'
import type { Player, Team } from '../core/types'
import { seedFromString } from '../core/rng'
import { loadRoster } from '../adapters/squad-library'
import { renderMatchVideo, slugify } from './render-pipeline'

const argv = process.argv.slice(2)
const flag = (name: string): string | undefined => {
  const eq = argv.find(a => a.startsWith(`--${name}=`))
  if (eq) return eq.split('=').slice(1).join('=')
  const i = argv.indexOf(`--${name}`)
  return i >= 0 ? argv[i + 1] : undefined
}

// Les deux premiers arguments non-option = les équipes. Les noms composés passent
// entre guillemets ("Saudi Arabia"), comme n'importe quelle commande shell.
const positional: string[] = []
for (let i = 0; i < argv.length; i++) {
  const a = argv[i]
  if (a.startsWith('--')) { if (!a.includes('=')) i++; continue }
  positional.push(a)
}
const [homeName, awayName] = positional

if (!homeName || !awayName) {
  console.log('Usage : npm run match -- <domicile> <extérieur> [--score H-A] [--competition "…"]')
  console.log('Exemple : npm run match -- Spain Portugal')
  process.exit(2)
}

const namespace = flag('namespace') ?? 'pronoclip'

function rosterOrNull(team: string): Player[] | null {
  try {
    return loadRoster(team, namespace)
  } catch {
    return null
  }
}

const homePlayers = rosterOrNull(homeName)
const awayPlayers = rosterOrNull(awayName)
const missing = [...(homePlayers ? [] : [homeName]), ...(awayPlayers ? [] : [awayName])]
if (missing.length > 0) {
  console.log(`\n⚠️  Effectif non semé pour : ${missing.join(', ')}`)
  console.log('   Les buteurs sont une ENTRÉE du moteur, jamais une invention du modèle.\n')
  console.log(`   Semer :  ${missing.map(t => `/pronoclip-squad ${t}`).join('\n            ')}`)
  console.log('\n   Ou, depuis un dossier de portraits déjà générés :')
  console.log('     npx tsx scripts/seed-squads-from-folder.ts "<dossier>"\n')
  process.exit(1)
}

const scoreArg = flag('score')
let score: { home: number; away: number } | undefined
if (scoreArg) {
  if (!/^\d+-\d+$/.test(scoreArg)) {
    console.log(`\n⚠️  Score « ${scoreArg} » mal formé (attendu H-A, ex. 2-1). Rien n'a été généré.\n`)
    process.exit(1)
  }
  const [h, a] = scoreArg.split('-').map(Number)
  score = { home: h, away: a }
}

const home: Team = { name: homeName, players: homePlayers!, colors: { primary: 'royal blue', secondary: 'white' } }
const away: Team = { name: awayName, players: awayPlayers!, colors: { primary: 'crimson', secondary: 'white' } }

const { mp4, script, durationMs, voiceProvider } = await renderMatchVideo({
  home, away,
  competition: flag('competition') ?? 'Match amical',
  seed: seedFromString(`${homeName}|${awayName}`),
  score,
  outBase: `pronoclip_${slugify(homeName)}-vs-${slugify(awayName)}`,
  voiceProvider: flag('voice') as never,
  log: m => console.log(m),
})

console.log(`\n===== MP4 FINAL (${Math.round(durationMs / 1000)} s, tier motion gratuit, voix ${voiceProvider}) =====`)
console.log(`${script.match.home} ${script.prediction.score.home}-${script.prediction.score.away} ${script.match.away}` +
  `  — score ${script.prediction.autoGenerated.score ? 'PRÉDIT' : 'imposé'} par le moteur LOCAL`)
console.log(mp4)
