// Assemblage du match-script.json (cf. MISSION §6).
// Le pronostic ne part JAMAIS directement en génération : il produit d'abord cet
// artefact relisible/corrigible (score, buteurs, types, ordre chrono, squelette
// des 8 plans, captions). Pur : aucune I/O — la sérialisation renvoie une chaîne,
// l'écriture disque est du ressort de l'appelant (adapters/CLI).

import type { MatchScript, PredictionInput } from './types'
import { predictMatch } from './prediction'
import { allocateShots } from './shot-budget'
import { randomSeed } from './rng'

/** Construit le match-script complet à partir d'une entrée de pronostic. */
export function buildMatchScript(input: PredictionInput): MatchScript {
  const knockout = input.knockout ?? false
  // Graine = paramètre d'entrée ; défaut ALÉATOIRE (jamais dérivée des noms).
  const seed = input.seed ?? randomSeed()

  const prediction = predictMatch({ ...input, seed })

  const keyPlayerName = (players: PredictionInput['home']['players']) =>
    (players.find(p => p.isKeyPlayer) ?? players[0])?.name

  const shots = allocateShots({
    home: { name: input.home.name, keyPlayer: keyPlayerName(input.home.players) },
    away: { name: input.away.name, keyPlayer: keyPlayerName(input.away.players) },
    score: prediction.score,
    goals: prediction.goals,
    knockout,
  })

  // Notes : signale (sans bloquer) les buteurs fournis absents de l'effectif.
  const notes: string[] = []
  const homeRoster = new Set(input.home.players.map(p => p.name))
  const awayRoster = new Set(input.away.players.map(p => p.name))
  for (const g of prediction.goals) {
    const roster = g.teamSide === 'home' ? homeRoster : awayRoster
    if (roster.size > 0 && !roster.has(g.playerName)) {
      notes.push(`Buteur « ${g.playerName} » absent de l'effectif ${g.teamSide} fourni.`)
    }
  }

  return {
    version: '1.0',
    generatedBy: 'pronoclip-video/core',
    match: {
      home: input.home.name,
      away: input.away.name,
      competition: input.competition,
      knockout,
    },
    inputLevel: prediction.inputLevel,
    seed,
    prediction: {
      score: prediction.score,
      autoGenerated: prediction.autoGenerated,
      goals: prediction.goals,
    },
    shots,
    notes,
  }
}

/** Sérialise un match-script en JSON indenté (prêt à écrire sur disque). */
export function serializeMatchScript(script: MatchScript): string {
  return JSON.stringify(script, null, 2) + '\n'
}
