// Domaine partagé du cœur pronoclip-video.
// Pur : ce module ne connaît ni MCP ni REST (cf. MISSION §10) et n'a aucune I/O.

/** Les 7 types de but autorisés (cf. MISSION §6). Vocabulaire figé. */
export type GoalType =
  | 'goal_normal'
  | 'goal_header'
  | 'goal_volley'
  | 'goal_bicycle'
  | 'goal_freekick'
  | 'goal_penalty'
  | 'goal_longrange'

export const GOAL_TYPES: readonly GoalType[] = [
  'goal_normal',
  'goal_header',
  'goal_volley',
  'goal_bicycle',
  'goal_freekick',
  'goal_penalty',
  'goal_longrange',
]

export type TeamSide = 'home' | 'away'

/** Tous les types de plan possibles dans le montage de 8 plans (cf. MISSION §4/§5). */
export type SceneType =
  | 'team_reveal'
  | 'rival_reveal'
  | 'face_off'
  | 'final_result'
  | 'power_up'
  | 'celebration'
  | 'determination'
  | 'goalkeeper_save'
  | 'big_chance_missed'
  | 'goal_montage'
  | GoalType

/**
 * Niveau d'entrée fourni par l'utilisateur (cf. MISSION §6) :
 * L0 = rien, L1 = score, L2 = score + buteurs, L3 = tout donné.
 * Règle dure : on ne prédit JAMAIS par-dessus une valeur fournie.
 */
export type InputLevel = 'L0' | 'L1' | 'L2' | 'L3'

/** Niveau de rendu (cf. MISSION §8) : `motion` (gratuit) ou `animated` (premium). */
export type RenderLevel = 'motion' | 'animated'

/** Poste du joueur — pilote les probabilités de type de but par défaut. */
export type Position = 'GK' | 'DF' | 'MF' | 'WG' | 'FW'

/**
 * Profil football d'un joueur (cf. MISSION correction §6bis). Sert à pondérer le
 * type de but : un ailier ne marque quasiment jamais de la tête, seul le tireur
 * désigné prend penaltys et coups francs. Toutes les stats sont dans [0,1].
 */
export interface PlayerProfile {
  position: Position
  /** Aptitude aérienne (têtes). Défaut dérivé du poste. */
  heading?: number
  /** Propension aux frappes lointaines. Défaut dérivé du poste. */
  longRange?: number
  /** Qualité sur coups francs (le tireur désigné a une valeur haute). Défaut 0. */
  setPieces?: number
  /** Tireur de penalty désigné. Seul lui peut marquer un `goal_penalty`. */
  isPenaltyTaker?: boolean
}

/** Un joueur de l'effectif fourni. Les buteurs ne sortent QUE d'ici (cf. MISSION §6). */
export interface Player {
  id?: string
  name: string
  isKeyPlayer?: boolean
  profile?: PlayerProfile
}

/** Couleurs d'équipe (aplat, sans écusson ni sponsor — cf. directives légales). */
export interface TeamColors {
  primary: string
  secondary?: string
}

/** Une équipe + son effectif fourni. `strength` (0..1) est optionnel : biais de score. */
export interface Team {
  name: string
  players: Player[]
  strength?: number
  colors?: TeamColors
}

export interface Score {
  home: number
  away: number
}

/** Contraintes de marché — entrées OPTIONNELLES (cf. MISSION §6). */
export interface MarketConstraints {
  result?: 'home' | 'draw' | 'away'
  btts?: 'yes' | 'no'
  ou25?: 'over' | 'under'
}

/** Un but pronostiqué, entièrement résolu. */
export interface GoalPrediction {
  matchOrder: number
  teamSide: TeamSide
  goalOrder: number
  playerId?: string
  playerName: string
  goalType: GoalType
}

/** But partiel fourni par l'utilisateur (L2 : sans type ; L3 : complet). */
export interface PartialGoal {
  teamSide: TeamSide
  matchOrder?: number
  playerName?: string
  goalType?: GoalType
}

/** Ce qui a été auto-généré vs fourni par l'utilisateur. */
export interface AutoGeneratedFlags {
  score: boolean
  scorers: boolean
  goalTypes: boolean
}

export interface Prediction {
  inputLevel: InputLevel
  score: Score
  goals: GoalPrediction[]
  autoGenerated: AutoGeneratedFlags
}

/** Entrée du moteur de pronostic. */
export interface PredictionInput {
  home: Team
  away: Team
  competition?: string
  knockout?: boolean
  /** Fourni → L1+. Absent → L0 (score auto). */
  score?: Score
  /** Fourni → L2+ (buteurs) et L3 (buteurs + types). */
  goals?: PartialGoal[]
  /** Contraintes de marché optionnelles. */
  market?: MarketConstraints
  /** Graine de reproductibilité. Absente → dérivée du nom des équipes. */
  seed?: number
}

/** Un plan du montage (8 au total). */
export interface Shot {
  order: number
  sceneType: SceneType
  teamSide: TeamSide | 'both' | null
  playerName: string | null
  caption: string
  goalType?: GoalType
  /** Pour `goal_montage` : les buts absorbés (cf. MISSION §5, G > 4). */
  mergedScorers?: { playerName: string; goalType: GoalType }[]
}

/**
 * Le « monde » — choisi UNE SEULE FOIS et identique mot pour mot dans les 8 prompts
 * (cf. MISSION §4). C'est ce verrou qui tue le bug nuit→orage→coucher de soleil.
 */
export interface WorldBible {
  time_of_day: string
  sky: string
  weather: string
  stadium: string
  floodlights: string
  crowd: string
  grade: string
}

/** Réglages caméra par type de plan (cf. MISSION §4). */
export interface CameraBible {
  format: string
  reveals: string
  duels: string
  closeups: string
  goals: string
}

/** Identité visuelle d'une équipe. L'aura vient TOUJOURS d'ici, jamais du fragment. */
export interface TeamKitBible {
  kit: string
  shorts: string
  socks: string
  aura: string
}

/**
 * Fiche personnage verrouillée d'un joueur (athlète fictif — Décision A2).
 * Reprise mot pour mot dans chaque plan où il apparaît. `number` est stocké pour
 * les overlays/métadonnées mais N'EST PAS peint dans l'image (no numbers).
 */
export interface PlayerBible {
  side: TeamSide
  build: string
  hair: string
  skin: string
  number: number
  boots: string
  reference_image_url: string | null
}

/** « Match Bible » : le monde verrouillé une fois, lu par les 8 plans (cf. MISSION §4). */
export interface MatchBible {
  world: WorldBible
  camera: CameraBible
  teams: { home: TeamKitBible; away: TeamKitBible }
  players: Record<string, PlayerBible>
  seed: number
}

/** L'artefact relisible/corrigible avant toute génération (cf. MISSION §6). */
export interface MatchScript {
  version: '1.0'
  generatedBy: 'pronoclip-video/core'
  match: {
    home: string
    away: string
    competition?: string
    knockout: boolean
  }
  inputLevel: InputLevel
  seed: number
  prediction: {
    score: Score
    autoGenerated: AutoGeneratedFlags
    goals: GoalPrediction[]
  }
  shots: Shot[]
  notes: string[]
}
